services:
  node:
    image: gitlab.innermedia.de:5050/outermedia/docker/node/node:24-dev
    volumes:
      - .:/application
    networks:
      default:
    ports:
      - "3000:3000"
    entrypoint: ./docker/development.entrypoint
    container_name: tba3-report

networks:
  default: